package org.jboss.camel.events;

import org.jboss.eventmonitor.*;

declare org.jboss.eventmonitor.Event
   @role(event)
   @timestamp(timestamp)
end;

rule "log"
when
#TODO: need to add a correlation ID in case two routes throw events in at the same time
    $e1 : Event($component:component, eventName=='start') from entry-point "EventStream"
    $e2 : Event(component==$component, eventName=='end') from entry-point "EventStream"
then
System.out.println("log fired! for component '"+$component+"'");
    String component=$e1.getComponent();
    long duration=$e2.getTimestamp()-$e1.getTimestamp();
    new CsvLogHandler().with("component",component).with("duration",duration).debug();
end

rule "max performance threshold of all routes"
when
    $e1 : Event($component:component, $eventName:eventName=='routeStart') from entry-point "EventStream"
    $e2 : Event(component==$component, eventName=='routeEnd',
        this after[0m1s] $e1) from entry-point "EventStream"
then
    System.out.println("EVENT ALERT: route ["+$component+"] exceeded threshold of 1s for event ["+$eventName+"]. took "+($e2.getTimestamp()-$e1.getTimestamp())+"ms.. notify everyone!");
    retract($e1);
    retract($e2);
end


